// src/localization/en.js
export default {
  // ========== COMMON ==========
  common: {
 "welcome": "مرحبًا",
  "signIn": "تسجيل الدخول",
  "next": "التالي",
  "back": "رجوع",
  "add": "إضافة",
  "cancel": "إلغاء",
  "save": "حفظ",
  "edit": "تعديل",
  "delete": "حذف",
  "print": "طباعة",
  "done": "تم",
  "close": "إغلاق",
  "year": "سنة",
  "select": "اختيار",
  "upload": "تحميل",
  "view": "عرض",
  "loading": "جاري التحميل...",
  "updating": "جاري التحديث...",
  "camera": "الكاميرا",
  "gallery": "المعرض",
  "minuteSuffix": "دقيقة",
  "noUserSelectedTitle": "لم يتم اختيار مستخدم",
  "noUserSelectedMessage": "يرجى اختيار مستخدم أولاً",
  "search": "بحث",
  "appName": "SafeNest",
  "noData": "لا توجد بيانات متاحة",
  "searchForChild": "البحث عن طفل",
  "ok": "موافق",
  "askMeLater": "اسألني لاحقًا",
  "reset": "إعادة تعيين",
  "filter": "تصفية",
  "applyFilter": "تطبيق التصفية",
  "price": "السعر",
  "enterPrice": "أدخل السعر",
  "dateOfBirth": "تاريخ الميلاد",
  "dateOfBirthPlaceholder": "YYYY/MM/DD",
  "phoneNumber": "رقم الهاتف",
  "phoneNumberPlaceholder": "XXXXXXXXXXX",

  },

  // ========== ADD MENU / SHORTCUTS ==========
  addMenu: {
   "addGame": "إضافة لعبة جديدة",
"addUser": "إضافة مستخدم جديد",
"registerChild": "تسجيل طفل جديد"
  },

  // ========== ADD GAME / REGISTER GAME ==========
  addGame: {
  "sectionTitle": "تسجيل لعبة جديدة",
"sectionSubtitle": "يرجى تعبئة تفاصيل اللعبة لإضافتها إلى النظام",
"gameName": "اسم اللعبة",
"gameNamePlaceholder": "Cricket",
"durationPlaceholder": "المدة",
"addMsgTitle": "إضافة رسالة",
"selectMessage": "اختر رسالة",
"registerButton": "تسجيل لعبة جديدة",
"success": "تم تسجيل اللعبة بنجاح",
  },

  // ========== AUTH & LOGIN ==========
  auth: {
   "welcome": "مرحبًا",
"signInToAccount": "تسجيل الدخول إلى حسابك",
"username": "اسم المستخدم",
"usernamePlaceholder": "اسم المستخدم",
"password": "كلمة المرور",
"passwordPlaceholder": "أدخل كلمة المرور",
"currentPassword": "كلمة المرور الحالية",
"newPassword": "كلمة المرور الجديدة",
"reEnterPassword": "إعادة إدخال كلمة المرور",
"changePassword": "تغيير كلمة المرور",
"changePasswordButton": "تغيير كلمة المرور",
"passwordsDoNotMatch": "كلمات المرور غير متطابقة",
"email": "البريد الإلكتروني",
"emailPlaceholder": "example@gmail.com",
"phoneNumber": "رقم الهاتف",
"phonePlaceholder": "XXXXXXXXXXX",
"forgotPassword": "هل نسيت كلمة المرور؟",
"loginError": "فشل تسجيل الدخول. يرجى المحاولة مرة أخرى.",
"loginSuccess": "تم تسجيل الدخول بنجاح",

"emailRequired": "البريد الإلكتروني مطلوب",
"emailInvalid": "يرجى إدخال عنوان بريد إلكتروني صالح",
"passwordRequired": "كلمة المرور مطلوبة",
"passwordMinLength": "يجب أن تتكون كلمة المرور من 6 أحرف على الأقل",

  },

  // ========== DASHBOARD ==========
  dashboard: {
    "title": "SafeNest",
"year": "سنة",
"numberOfChildrenRegisteredWeekly": "عدد الأطفال المسجلين أسبوعيًا",
"childrenCount": "700 طفل",
"value": "500,000",
"budget": "الميزانية",
"numberOfChildren": "عدد الأطفال",
"children": "الأطفال",
"currentDate": "15 أبريل 2025",
"loadMore": "تحميل المزيد",
"endSession": "إنهاء الجلسة",
"deliver": "تسليم",
"quickActions": "إجراءات سريعة",
"totalPlaytimePrefix": "إجمالي وقت اللعب:",
"guardianPrefix": "ولي الأمر:",
  },

  // ========== MANUAL HANDOVER / SCANNER ==========
  manualHandover: {
    "title": "التسليم اليدوي",
"cameraRequired": "إذن الكاميرا مطلوب",
"scanCode": "مسح الرمز"
  },

  // ========== USER REGISTRATION ==========
  user: {
   "identityInformation": "معلومات الهوية",
"accountType": "نوع الحساب",
"userInformation": "معلومات المستخدم",
"accountInformation": "معلومات الحساب",
"firstName": "الاسم الأول",
"firstNamePlaceholder": "الاسم الأول",
"secondName": "الاسم الثاني (اختياري)",
"secondNamePlaceholder": "الاسم الثاني",
"thirdName": "الاسم الثالث (اختياري)",
"thirdNamePlaceholder": "الاسم الثالث",
"fourthName": "الاسم الرابع (اختياري)",
"fourthNamePlaceholder": "الاسم الرابع",
"lastName": "اسم العائلة (اختياري)",
"lastNamePlaceholder": "اسم العائلة",
"nationalId": "بطاقة الهوية الوطنية",
"nationalIdPlaceholder": "أدخل رقم الهوية الوطنية",
"nationalIdImage": "صورة بطاقة الهوية الوطنية",
"nickname": "الاسم المستعار",
"nationalIdImagePlaceholder": "تحميل بطاقة الهوية الوطنية",
"residenceCard": "بطاقة الإقامة",
"residenceCardPlaceholder": "أدخل رقم بطاقة الإقامة",
"residenceCardImage": "صورة بطاقة الإقامة",
"residenceCardImagePlaceholder": "تحميل بطاقة الإقامة",
"manager": "مدير",
"user": "مستخدم",
"managerDescription": "هذا الحساب مخصص للمديرين. يتيح لك الإشراف على المستخدمين، وإدارة الأنشطة، والوصول إلى التحليلات العامة.",
"userDescription": "هذا الحساب مخصص لموظفي منطقة اللعب. يتيح لك تسجيل حضور الأطفال، وإدارة جلسات اللعب، والتواصل مع أولياء الأمور.",
  },

  // ========== CHILD REGISTRATION ==========
  child: {
    "registerNewChild": "تسجيل طفل جديد",
"childDetails": "تفاصيل الطفل",
"sessionDetails": "تفاصيل الجلسة",
"childName": "اسم الطفل",
"childNamePlaceholder": "اسم الطفل",
"guardianName": "اسم ولي الأمر",
"guardianNamePlaceholder": "اسم ولي الأمر",
"dateOfBirth": "تاريخ الميلاد",
"dateOfBirthPlaceholder": "YYYY/MM/DD",
"address": "العنوان",
"addressPlaceholder": "العنوان",
"gender": "الجنس",
"male": "ذكر",
"female": "أنثى",
"uploadChildPhoto": "تحميل صورة الطفل",
"addImageHere": "أضف صورة هنا",
"addMore": "+ إضافة المزيد",
"attachment": "مرفق",
"assignChildToStaff": "تعيين الطفل إلى الموظف",
"assignChildToStaffPlaceholder": "تعيين الطفل إلى الموظف",
"phonePlaceholder": "xxxxxxxxxx",

"childRegisteredSuccess": "تم تسجيل الطفل بنجاح",
"childRegisteredMessage": "تم تسجيل الطفل بنجاح ويمكنه الآن بدء جلسة اللعب.\nيرجى طباعة رمز الباركود الخاص بالطفل.",

//Model Labels

"childNameLabel": "اسم الطفل",
"guardianLabel": "ولي الأمر",
"phoneNumberLabel": "رقم الهاتف",
"sessionEndDuration": "مدة انتهاء الجلسة",
"sessionDuration": "مدة الجلسة",
"sessionPrice": "سعر الجلسة",
"sessionEndDurationLabel": "مدة انتهاء الجلسة",
"no": "رقم",
"userNameLabel": "اسم المستخدم",
"addressLabel": "العنوان",
"playHoursLabel": "ساعات اللعب",
"statusLabel": "الحالة",
  },

  confirmation: {
    "title": "تأكيد",

  },

  handover: {
   "confirm": "تأكيد تسليم الطفل",

  },

  // ========== USER LIST / TABLE ==========
  userList: {
    "no": "رقم",
"userName": "اسم المستخدم",
"phoneNumber": "رقم الهاتف",
"email": "البريد الإلكتروني",
"selectAll": "تحديد الكل",
"deleteSelected": "حذف المحدد",
"noDataAvailable": "لا توجد بيانات متاحة",
"searchPlaceholder": "البحث عن مستخدم",
"confirmDeleteTitle": "تأكيد الحذف",
"confirmDeleteMessage": "هل أنت متأكد أنك تريد حذف {count} مستخدم(ين)؟",
"noUserSelectedTitle": "لم يتم اختيار مستخدم",
"noUserSelectedMessage": "يرجى تحديد مستخدم واحد على الأقل للحذف.",
"userDeletedSuccess": "تم حذف المستخدمين بنجاح.",
"failedToDeleteUsers": "فشل في حذف المستخدمين.",

  },

  // ========== SESSION DETAILS ==========
  session: {
    sessionDetails: "Session Details",
    "gameType": "نوع اللعبة",
"selectGameType": "اختر نوع اللعبة",
"playTimeFrom": "وقت اللعب من",
"playTimeTo": "وقت اللعب إلى",
"sessionDate": "تاريخ الجلسة",
"playDuration": "مدة اللعب",
"timePlaceholder": "HH/MM",
"datePlaceholder": "YYYY/MM/DD",
"delivered": "تم التسليم",
"waiting": "قيد الانتظار",
"activeNow": "نشط الآن",
  },

  // ========== VALIDATION ==========
  validation: {
   "required": "هذا الحقل مطلوب",
"emailRequired": "البريد الإلكتروني مطلوب",
"emailInvalid": "يرجى إدخال عنوان بريد إلكتروني صالح",
"passwordRequired": "كلمة المرور مطلوبة",
"passwordMinLength": "يجب أن تتكون كلمة المرور من 6 أحرف على الأقل",
"phoneRequired": "رقم الهاتف مطلوب",
"phoneInvalid": "يرجى إدخال رقم هاتف صالح",
"nameRequired": "الاسم مطلوب",
"guardianNameRequired": "اسم ولي الأمر مطلوب",
"dateOfBirthRequired": "تاريخ الميلاد مطلوب",
"addressRequired": "العنوان مطلوب",
"genderRequired": "الجنس مطلوب",
"nationalIdRequired": "الهوية الوطنية مطلوبة",
"nationalIdImageRequired": "صورة الهوية الوطنية مطلوبة",
"residenceCardRequired": "بطاقة الإقامة مطلوبة",
"residenceCardImageRequired": "صورة بطاقة الإقامة مطلوبة",
"gameTypeRequired": "نوع اللعبة مطلوب",
"sessionDateRequired": "تاريخ الجلسة مطلوب",
"playFromRequired": "وقت اللعب (من) مطلوب",
"playToRequired": "وقت اللعب (إلى) مطلوب",
"durationRequired": "المدة مطلوبة",
"firstNameRequired": "الاسم الأول مطلوب",
"secondNameRequired": "الاسم الثاني مطلوب",
"nicknameRequired": "الاسم المستعار مطلوب",
"playToGreaterThanPlayFromTitle": "التحقق",
"playToGreaterThanPlayFrom": "يجب أن يكون وقت اللعب (إلى) أكبر من وقت اللعب (من)",
  },

  // ========== BUTTONS ==========
  buttons: {
   "signIn": "تسجيل الدخول",
"next": "التالي",
"back": "رجوع",
"add": "إضافة",
"save": "حفظ",
"cancel": "إلغاء",
"delete": "حذف",
"edit": "تعديل",
"print": "طباعة",
"done": "تم",
"viewAccount": "عرض الحساب",
"view": "عرض",
"upload": "تحميل",

  },
splash:{
  "splash_center1": "مرحبًا بك في نظام إدارة الألعاب",
"splash_center2": "يرجى تسجيل الدخول للمتابعة",
"get_started": "ابدأ الآن"
},
  // ========== SETTINGS ==========
  settings: {
   "title": "الإعدادات",
"manageAccount": "إدارة إعدادات وتفضيلات حسابك",
"selectOption": "اختر خيارًا",
"chooseImageSource": "اختر مصدر الصورة",
"profileUpdatedSuccess": "تم تحديث الملف الشخصي بنجاح!",
"accountManagementTitle": "إدارة الحساب",
"saveChanges": "حفظ التغييرات",
"whatsappConnectedSuccess": "تم ربط واتساب بنجاح",
"whatsappInvalidOtp": "رمز التحقق غير صالح أو منتهي الصلاحية",
"otpSent": "تم إرسال رمز تحقق جديد",
"otpResendFailed": "فشل في إعادة إرسال رمز التحقق",
"verifyOtpTitle": "التحقق من رمز التحقق",
"enterOtpTitle": "إدخال رمز التحقق",
"enterOtpSubtitle": "يرجى إدخال رمز التحقق المرسل إلى رقم واتساب الخاص بك",
"enterOtpPlaceholder": "أدخل رمز التحقق",
"resendOtp": "إعادة إرسال رمز التحقق",
"verifyOtpButton": "التحقق من رمز التحقق",
"whatsappEnabled": "واتساب مفعّل",
"whatsappDisabled": "واتساب غير مفعّل",
"whatsappUpdateFailed": "فشل في تحديث واتساب",
"invalidPhoneNumber": "أدخل رقم هاتف صالحًا مع رمز الدولة",
"otpSendFailed": "فشل في إرسال رمز التحقق",
"whatsappManagementTitle": "إدارة واتساب",
"whatsappInfo": "يرجى إدخال رقم الهاتف المرتبط بخدمة واتساب لإكمال الاتصال واستلام رمز التفعيل.",
"phonePlaceholder": "+91XXXXXXXXXX",
"sendOtpButton": "إرسال رمز التحقق",
"whatsappNotInstalled": "واتساب غير مثبت على جهازك",
"deleteAccountTitle": "حذف الحساب",
"deleteAccountMessage": "هل أنت متأكد أنك تريد حذف حسابك؟",
"accountManagement": "إدارة الحساب",
"changePassword": "تغيير كلمة المرور",
"whatsappManagement": "إدارة واتساب",
"messageManagement": "إدارة الرسائل",
"gameManagement": "إدارة الألعاب",
"resendOtpTimer": "إعادة إرسال رمز التحقق خلال",
"whatsappText": "واتساب",
"whatsappSubtext": "ربط التطبيق بخدمة واتساب",
  },

  // ========== MODALS ==========
  modal: {
   "accountDetails": "تفاصيل الحساب",
"accountCreationCard": "بطاقة إنشاء الحساب",
"accountCreatedTitle": "تم إنشاء الحساب بنجاح",
"accountCreatedDesc1": "يمكنك الآن استخدام بيانات تسجيل الدخول التي أدخلتها للوصول إلى النظام.",
"accountCreatedDesc2": "يرجى التأكد من مشاركة اسم المستخدم وكلمة المرور مع صاحب الحساب.",
"done": "تم",
"viewAccount": "عرض الحساب"
  },

  // ========== PICKERS ==========
  picker: {
   "selectMinute": "اختر دقيقة",
"selectMinutes": "اختر الدقائق"
  },

  // ========== ALERTS & MESSAGES ==========
  alerts: {
  "deleteConfirm": "هل أنت متأكد أنك تريد الحذف؟",
"success": "نجاح",
"error": "خطأ",
"warning": "تحذير",
"info": "معلومات",
"childRegisteredTitle": "تم تسجيل الطفل الآن!",
"childRegisteredMessage": "تم تسجيل الطفل بنجاح ويمكنه الآن بدء جلسة اللعب.\nيرجى طباعة رمز الباركود الخاص بالطفل.",
"accountDeleted": "تم حذف الحساب",
"sessionExpiredTitle": "انتهت الجلسة",
"sessionExpiredMessage": "انتهت صلاحية تسجيل الدخول. يرجى تسجيل الدخول مرة أخرى.",
  },

  // ========== MESSAGE MANAGEMENT ==========
  messageManagement: {
   "title": "إدارة الرسائل",
"savedMessages": "الرسائل المحفوظة",
"createMessage": "إنشاء رسالة جديدة",
"edit": "تعديل",
"delete": "حذف",
"deleteConfirm": "هل أنت متأكد أنك تريد حذف هذا؟",
"cancel": "إلغاء",
"selectType": "اختر نوع الرسالة",
"selectMessage": "اختر رسالة",
"messageName": "اسم الرسالة",
"messageContent": "محتوى الرسالة",
"save": "حفظ الرسالة",
"update": "تحديث الرسالة",
"endWork": "نهاية ساعات العمل",
"alert": "رسالة تنبيه",
"reward": "رسالة مكافأة",
"general": "رسالة عامة",
"endTime": "وقت الانتهاء (بالدقائق)",
"sendTime": "وقت الإرسال (HHMM)",
"successSaved": "تم حفظ الرسالة بنجاح",
"successUpdated": "تم تحديث الرسالة بنجاح",
"successDeleted": "تم حذف الرسالة بنجاح",
"required": "هذا الحقل مطلوب",
"saving": "جارٍ الحفظ...",
"minutesBefore": "دقائق قبل انتهاء الجلسة",
"whenPlaceCloses": "عند إغلاق المكان",
"afterSession": "بعد انتهاء الجلسة",
"beforeSession": "قبل انتهاء الجلسة",
"rewardHelper": "تُرسل لتحفيز الأطفال عند اللعب لفترات طويلة أو عند الحصول على خصم.",
"generalHelper": "رسائل ترحيب أو إعلانات",
"sendDate": "تاريخ الإرسال",
"saveFailed": "تعذر حفظ الرسالة",
"beforeSession": "قبل بدء الجلسة",
"afterSession": "بعد انتهاء الجلسة",
"sendingTime": "وقت الإرسال",
"endOfWorkingHoursTime": "وقت نهاية ساعات العمل",
"whenPlaceCloses": "عند إغلاق المكان",
  },
};
