// src/localization/en.js
export default {
  // ========== COMMON ==========
  common: {
    welcome: "Welcome",
    signIn: "Sign In",
    next: "Next",
    back: "Back",
    add: "Add",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    print: "Print",
    done: "Done",
    close: "Close",
    year: "Year",
    select: "Select",
    upload: "Upload",
    view: "View",
    loading: "Loading...",
  updating: "Updating...",
  camera: "Camera",
  gallery: "Gallery",
  minuteSuffix: "min",
  noUserSelectedTitle: 'No user selected',
  noUserSelectedMessage: 'Please select a user first',
    search: "Search",
  appName: "SafeNest",
  noData: "No data available",
  searchForChild: "Search for a child",
  ok: "OK",
  askMeLater: "Ask Me Later",
  reset:'Reset',
  filter:'Filter',
  applyFilter:'Apply Filter',
  price:'Price',
  enterPrice:'Enter Price',
  dateOfBirth:'Date of Birth',
  dateOfBirthPlaceholder:'YYYY/MM/DD',
  phoneNumber:'Phone Number',
  phoneNumberPlaceholder:'XXXXXXXXXXX',

  },

  // ========== ADD MENU / SHORTCUTS ==========
  addMenu: {
    addGame: "Add a new game",
    addUser: "Add a new user",
    registerChild: "Register a new child",
  },

  // ========== ADD GAME / REGISTER GAME ==========
  addGame: {
    sectionTitle: "Register a new game",
    sectionSubtitle: "Please fill in the game details to add it to the system",
    gameName: "Game name",
    gameNamePlaceholder: "Cricket",
    durationPlaceholder: "Duration",
    addMsgTitle: "Add message",
    selectMessage: "Select message",
    registerButton: "Register a new game",
    success:'The game has been registered successfully'
  },

  // ========== AUTH & LOGIN ==========
  auth: {
    welcome: "Welcome",
    signInToAccount: "Sign in to your account",
    username: "Username",
    usernamePlaceholder: "Username",
    password: "Password",
    passwordPlaceholder: "Enter password",
  currentPassword: "Current Password",
  newPassword: "New Password",
  reEnterPassword: "Re-Enter Password",
  changePassword: "Change Password",
  changePasswordButton: "Change Password",
  passwordsDoNotMatch: "Passwords do not match",
    email: "Email",
    emailPlaceholder: "example@gmail.com",
    phoneNumber: "Phone Number",
    phonePlaceholder: "XXXXXXXXXXX",
    forgotPassword: "Forgot Password?",
    loginError: "Login failed. Please try again.",
    loginSuccess: "Login successful",
    // Validation messages
    emailRequired: "Email is required",
    emailInvalid: "Please enter a valid email address",
    passwordRequired: "Password is required",
    passwordMinLength: "Password must be at least 6 characters",
  },

  // ========== DASHBOARD ==========
  dashboard: {
    title: "SafeNest",
    year: "Year",
    numberOfChildrenRegisteredWeekly: "Number of Children Registered Weekly",
    childrenCount: "700 Children",
    value: "500,000",
    budget: "Budget",
    numberOfChildren: "عدد الأطفال", // Arabic text - should be translated
    children: "Children",
  currentDate: "2025 April 15",
  loadMore: "Load More",
  endSession: "End Session",
  deliver: "Deliver",
  quickActions: "Quick Actions",
  totalPlaytimePrefix: "Total Playtime:",
  guardianPrefix: "Guardian:",
  },

  // ========== MANUAL HANDOVER / SCANNER ==========
  manualHandover: {
    title: "Manual Handover",
    cameraRequired: "Camera permission is required",
    scanCode: "Scan Code",
  },

  // ========== USER REGISTRATION ==========
  user: {
    identityInformation: "Identity Information",
    accountType: "Account Type",
    userInformation: "User Information",
    accountInformation: "Account Information",
    firstName: "First Name",
    firstNamePlaceholder: "First Name",
    secondName: "Second Name (Optional)",
    secondNamePlaceholder: "Second Name",
    thirdName: "Third Name (Optional)",
    thirdNamePlaceholder: "Third Name",
    fourthName: "Fourth Name (Optional)",
    fourthNamePlaceholder: "Fourth Name",
    lastName: "Last Name(optional)",
    lastNamePlaceholder: "Last Name",
    nationalId: "National ID Card",
    nationalIdPlaceholder: "Enter National ID Number",
    nationalIdImage: "National ID Card Image",
  nickname: "Nickname",
    nationalIdImagePlaceholder: "Upload National ID Card",
    residenceCard: "Residence Card",
    residenceCardPlaceholder: "Enter Residence Card Number",
    residenceCardImage: "Residence  Card Image",
    residenceCardImagePlaceholder: "Upload Residence Card",
    manager: "Manager",
    user: "User",
    managerDescription: "This account is intended for managers. It allows you to oversee users, manage activities, and access overall analytics.",
    userDescription: "This account is intended for staff within the play area. It allows you to record children's attendance, manage play sessions, and communicate with parents.",
  },

  // ========== CHILD REGISTRATION ==========
  child: {
    registerNewChild: "Register New Child",
    childDetails: "Child Details",
    sessionDetails: "Session Details",
    childName: "Child Name",
    childNamePlaceholder: "Child Name",
    guardianName: "Guardian Name",
    guardianNamePlaceholder: "Guardian Name",
    dateOfBirth: "Date of Birth",
    dateOfBirthPlaceholder: "YYYY/MM/DD",
    address: "Address",
    addressPlaceholder: "Address",
    gender: "Gender",
    male: "Male",
    female: "Female",
    uploadChildPhoto: "Upload child's photo",
    addImageHere: "Add Image Here",
    addMore: "+ Add More",
    attachment: "Attachment",
    assignChildToStaff: "Assign Child to Staff",
    assignChildToStaffPlaceholder: "Assign Child to Staff",
    phonePlaceholder: "xxxxxxxxxx",
    // Success messages
    childRegisteredSuccess: "The child has been registered now!",
    childRegisteredMessage: "The child has been successfully registered and can now start the play session.\nPlease print the child's barcode.",
    // Modal labels
    childNameLabel: "Child Name",
    guardianLabel: "Guardian",
    phoneNumberLabel: "Phone Number",
    sessionEndDuration: "Session End Duration",
    sessionDuration: "Session Duration",
    sessionPrice: "Session Price",
    sessionEndDurationLabel: "Session End Duration",
  no: "No.",
  userNameLabel: "User Name",
  addressLabel: "Address",
  playHoursLabel: "Play Hours",
  statusLabel: "Status",
  },

  confirmation: {
    title: "Confirmation",
  },

  handover: {
    confirm: "Confirm Child Handover",
  },

  // ========== USER LIST / TABLE ==========
  userList: {
    no: "No.",
    userName: "UserName",
    phoneNumber: "Phone Number",
    email: "Email",
    selectAll: "Select All",
    deleteSelected: "Delete Selected",
    noDataAvailable: "No data available",
    searchPlaceholder: "Search for a user",
    confirmDeleteTitle: "Confirm Delete",
    confirmDeleteMessage: "Are you sure you want to delete {count} user(s)?",
    noUserSelectedTitle: "No user selected",
    noUserSelectedMessage: "Please select at least one user to delete.",
    userDeletedSuccess: "User(s) deleted successfully.",
    failedToDeleteUsers: "Failed to delete users.",
  },

  // ========== SESSION DETAILS ==========
  session: {
    sessionDetails: "Session Details",
    gameType: "Game Type",
    selectGameType: "Select Game Type",
    playTimeFrom: "Play Time From",
    playTimeTo: "Play Time To",
    sessionDate: "Session Date",
    playDuration: "Play Duration",
    timePlaceholder: "HH/MM",
    datePlaceholder: "YYYY/MM/DD",
  delivered: "Delivered",
  waiting: "Waiting",
  activeNow: "Active Now",
  },

  // ========== VALIDATION ==========
  validation: {
    required: "This field is required",
    emailRequired: "Email is required",
    emailInvalid: "Please enter a valid email address",
    passwordRequired: "Password is required",
    passwordMinLength: "Password must be at least 6 characters",
    phoneRequired: "Phone number is required",
    phoneInvalid: "Please enter a valid phone number",
    nameRequired: "Name is required",
    guardianNameRequired: "Guardian name is required",
    dateOfBirthRequired: "Date of birth is required",
    addressRequired: "Address is required",
    genderRequired: "Gender is required",
    nationalIdRequired: "National ID is required",
    nationalIdImageRequired: "National ID image is required",
    residenceCardRequired: "Residence card is required",
    residenceCardImageRequired: "Residence card image is required",
    gameTypeRequired: "Game type is required",
    sessionDateRequired: "Session date is required",
    playFromRequired: "Play time from is required",
    playToRequired: "Play time to is required",
    durationRequired: "Duration is required",
  firstNameRequired: "First name is required",
  secondNameRequired: "Second name is required",
  nicknameRequired: "Nickname is required",
  playToGreaterThanPlayFromTitle: 'Validation',
  playToGreaterThanPlayFrom: 'Play To must be greater than Play From',
  },

  // ========== BUTTONS ==========
  buttons: {
    signIn: "Sign In",
    next: "Next",
    back: "Back",
    add: "Add",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    print: "Print",
    done: "Done",
    viewAccount: "View Account",
    view: "View",
    upload: "Upload",
  },
splash:{
  splash_center1: "Welcome to the Game Management System",
  splash_center2: "Please sign in to continue",
  get_started: "Start Now",
},
  // ========== SETTINGS ==========
  settings: {
    title: "Settings",
    manageAccount: "Manage your account settings and preferences",
    selectOption: "Select Option",
    chooseImageSource: "Choose image source",
    profileUpdatedSuccess: "Profile updated successfully!",
    accountManagementTitle: "Account Management",
    saveChanges: "Save Changes",
  whatsappConnectedSuccess: "WhatsApp connected successfully",
  whatsappInvalidOtp: "Invalid or expired OTP",
  otpSent: "A new OTP has been sent",
  otpResendFailed: "Failed to resend OTP",
  verifyOtpTitle: "Verify OTP",
  enterOtpTitle: "Enter OTP",
  enterOtpSubtitle: "Please enter the OTP sent to your WhatsApp number",
  enterOtpPlaceholder: "Enter OTP",
  resendOtp: "Resend OTP",
  verifyOtpButton: "Verify OTP",
  whatsappEnabled: "WhatsApp enabled",
  whatsappDisabled: "WhatsApp disabled",
  whatsappUpdateFailed: "Failed to update WhatsApp",
  invalidPhoneNumber: "Enter valid phone number with country code",
  otpSendFailed: "Failed to send OTP",
  whatsappManagementTitle: "WhatsApp Management",
  whatsappInfo: "Please enter the phone number linked to the WhatsApp service to complete the connection and receive the activation code.",
  phonePlaceholder: "+91XXXXXXXXXX",
  sendOtpButton: "Send OTP",
  whatsappNotInstalled: "WhatsApp is not installed on your device",
  deleteAccountTitle: "Delete Account",
  deleteAccountMessage: "Are you sure you want to delete your account?",  
  accountManagement: "Account Management",
  changePassword: "Change Password",
  whatsappManagement: "WhatsApp Management",
  messageManagement: "Message Management",
  gameManagement: "Game Management",
  resendOtpTimer: "Resend OTP in",
  whatsappText: "WhatsApp",
  whatsappSubtext: "Connect the application to the WhatsApp service",
  },

  // ========== MODALS ==========
  modal: {
    accountDetails: "Account Details",
    accountCreationCard: "Account creation card",
    accountCreatedTitle: "The account has been created successfully",
    accountCreatedDesc1: "You can now use the login credentials you entered to access the system.",
    accountCreatedDesc2: "Make sure to share the username and password with the owner.",
    done: "Done",
    viewAccount: "View account",
  },

  // ========== PICKERS ==========
  picker: {
    selectMinute: "Select Minute",
    selectMinutes: "Select Minutes",
  },

  // ========== ALERTS & MESSAGES ==========
  alerts: {
    deleteConfirm: "Are you sure you want to delete this?",
    success: "Success",
    error: "Error",
    warning: "Warning",
    info: "Information",
    childRegisteredTitle: "The child has been registered now!",
    childRegisteredMessage: "The child has been successfully registered and can now start the play session.\nPlease print the child's barcode.",
  accountDeleted: "Account Deleted",
  sessionExpiredTitle: "Session Expired",
  sessionExpiredMessage: "Your login has expired. Please login again.",
  },

  // ========== MESSAGE MANAGEMENT ==========
  messageManagement: {
    title: "Message Management",
    savedMessages: "Saved Messages",
    createMessage: "Create New Message",
    edit: "Edit",
    delete: "Delete",
    deleteConfirm: "Are you sure you want to delete this?",
    cancel: "Cancel",
    selectType: "Select Message Type",
    selectMessage: "Select message",
    messageName: "Message Name",
    messageContent: "Message Content",
    save: "Save Message",
    update: "Update Message",
    endWork: "End of the working hours",
    alert: "Alert Message",
    reward: "Reward Message",
    general: "General Message",
    endTime: "End Time (minutes)",
    sendTime: "Send Time (HHMM)",
    successSaved: "Message saved successfully",
    successUpdated: "Message updated successfully",
    successDeleted: "Message deleted successfully",
    required: "This field is required",
  saving: "Saving...",
  minutesBefore: "minutes before the session ends",
  whenPlaceCloses: "When the place closes",
  afterSession: "After the session ends",
  beforeSession: "Before the session ends",
  rewardHelper: "Sent to motivate children when they play for long periods or receive a discount.",
  generalHelper: "Welcome Messages or Announcements",
  sendDate: "Sending Date",
  saveFailed: "Could not save message",
  beforeSession: "Before the session starts",
  afterSession: "After the session ends",
  sendingTime: "Sending Time",
  endOfWorkingHoursTime: "End of Working Hours Time",
  whenPlaceCloses: "When the place closes",
  


  },
};
